/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/**
 * Gorilla Unleashed - extensions bundled INTO the browser.
 *
 * GENERATED by working scripts/add_builtin_extension.py. Do not hand-edit;
 * re-run the tool instead.
 *
 * WHY THIS FILE EXISTS
 *   This build blocks every add-on install route on purpose (07.TOOLKIT, the
 *   "API LOBOTOMY"). Nothing can be added from outside. That policy is not
 *   changed here - this registers extensions that ship INSIDE the package,
 *   which is a different thing entirely.
 *
 * WHY maybeInstallBuiltinAddon AND NOT built_in_addons.json
 *   Firefox has two built-in locations. The one driven by built_in_addons.json
 *   is `app-builtin-addons`, whose location object hard-codes
 *   `get hidden() { return true; }` - the add-on loads and runs but never
 *   appears in about:addons and has no toolbar button. That was tried first
 *   and is useless for anything a user needs to configure.
 *
 *   maybeInstallBuiltinAddon() installs into `app-builtin`, whose location
 *   returns `hidden: false`. Visible, manageable, toggleable.
 *
 * WHY IT DOES NOT TRIP THE LOBOTOMY
 *   The blocks are in AddonInstall.install() and a directory installer's
 *   installAddon(). This path reaches neither - BuiltInLocation.makeInstaller()
 *   returns a no-op installer, and installBuiltinAddon() goes straight to
 *   loadManifest() and _activateAddon().
 */

const lazy = {};

ChromeUtils.defineESModuleGetters(lazy, {
  AddonManager: "resource://gre/modules/AddonManager.sys.mjs",
});

/** Extensions bundled into this build. */
const BUNDLED = [
  {
    id: "uBlock0@raymondhill.net",
    version: "1.74.0",
    resourceURI: "resource://gorilla-addons/ublock-origin/",
    widgetId: "ublock0_raymondhill_net-browser-action",
  },
];

/**
 * Pin an extension's toolbar button once, the first time it is seen.
 *
 * Only ONCE: after that the user's own choice wins. A browser that re-pins a
 * button the user deliberately removed, on every startup, is a browser that
 * argues with its owner.
 */
const PINNED_PREF = "gorilla.builtinExtensions.pinned";

export const GorillaBuiltinExtensions = {
  async install() {
    for (const ext of BUNDLED) {
      try {
        await lazy.AddonManager.maybeInstallBuiltinAddon(
          ext.id,
          ext.version,
          ext.resourceURI
        );
      } catch (e) {
        console.error(`GorillaBuiltinExtensions: ${ext.id} failed to install`, e);
      }
    }
  },

  /**
   * Put the button on the toolbar rather than leaving it inside the
   * puzzle-piece overflow panel.
   *
   * This matters more here than in stock Firefox. Normal users look for an
   * extension in exactly two places - the toolbar and about:addons - and in a
   * browser where they cannot install anything, an ad blocker they cannot find
   * is an ad blocker they will assume is missing.
   */
  pinToToolbar(window) {
    let already = [];
    try {
      already = Services.prefs.getStringPref(PINNED_PREF, "").split(",").filter(Boolean);
    } catch (e) {}

    const { CustomizableUI } = window;
    if (!CustomizableUI) {
      return;
    }
    let changed = false;
    for (const ext of BUNDLED) {
      if (!ext.widgetId || already.includes(ext.id)) {
        continue;
      }
      try {
        // Only place it if it is not already somewhere the user put it.
        if (!CustomizableUI.getPlacementOfWidget(ext.widgetId)) {
          CustomizableUI.addWidgetToArea(
            ext.widgetId,
            CustomizableUI.AREA_NAVBAR
          );
        }
        already.push(ext.id);
        changed = true;
      } catch (e) {
        console.error(`GorillaBuiltinExtensions: could not pin ${ext.id}`, e);
      }
    }
    if (changed) {
      Services.prefs.setStringPref(PINNED_PREF, already.join(","));
    }
  },
};
